### ISSUE TITLE
Execute stop on Saturday and Sunday

### ISSUE THREAD

**Issue by gogosub77** [gogosub77/lambdaEC2AutoStartStop#1]
Now do not stop on Saturday and Sunday.
So fix it to run.

**Comment by gogosub77** [comment]
when fix?

**Comment by gogosub77** [comment]
完了

**Comment by anhtaka** [comment]
before      
              var dayoff = getDayOffBootFlg(instance, 'DayOffBoot')
after
              var dayoff = getDayOffBootFlg(instance, 'DayOffBoot');
